services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
networks:   
  default: 
    name: roboshop
    driver: bridge
    external: false # True if the network is created manually using docker network command.